<?php
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */

 // Add MaxFu Options to Sparkling Theme Customizer.
 function sparkling_customizer_maxfu_addon( $wp_customize ) {
   // add "MaxFu Options" panel
     $wp_customize->add_panel('sparkling_maxfu_options', array(
         'capability' => 'edit_theme_options',
         'theme_supports' => '',
         'title' => __('MaxFu Options', 'sparkling'),
         'description' => __('Panel to update MaxFu theme options', 'sparkling'), // Include html tags such as <p>.
         'priority' => 10 // Mixed with top-level-section hierarchy.
     ));

     // add "Layout Options" section
     $wp_customize->add_section( 'sparkling_maxfu_slider_section' , array(
             'title'      => esc_html__( 'Slider Options', 'sparkling' ),
             'priority'   => 50,
             'panel' => 'sparkling_maxfu_options'
     ));

     // add "Frontpage Title Options" option
     $wp_customize->add_setting( 'sparkling[hide_caption]', array(
             'default' => 0,
             'type' => 'option',
             'sanitize_callback' => 'sparkling_sanitize_checkbox',
     ));
     $wp_customize->add_control( 'sparkling[hide_caption]', array(
             'label'	=> esc_html__( 'Check if you want to hide the caption on sliders', 'sparkling' ),
             'section'	=> 'sparkling_maxfu_slider_section',
             'type'      => 'checkbox',
     ));

     // add "Layout Options" section
     $wp_customize->add_section( 'sparkling_maxfu_layout_section' , array(
             'title'      => esc_html__( 'Layout Options', 'sparkling' ),
             'priority'   => 50,
             'panel' => 'sparkling_maxfu_options'
     ));

     // add "Frontpage Title Options" option
     $wp_customize->add_setting( 'sparkling[frontpage_title]', array(
             'default' => 0,
             'type' => 'option',
             'sanitize_callback' => 'sparkling_sanitize_checkbox',
     ));
     $wp_customize->add_control( 'sparkling[frontpage_title]', array(
             'label'	=> esc_html__( 'Check if you want to display the title on front page', 'sparkling' ),
             'section'	=> 'sparkling_maxfu_layout_section',
             'type'      => 'checkbox',
     ));

     // add "Frontpage Title Options" option
     $wp_customize->add_setting( 'sparkling[title_center]', array(
             'default' => 0,
             'type' => 'option',
             'sanitize_callback' => 'sparkling_sanitize_checkbox',
     ));
     $wp_customize->add_control( 'sparkling[title_center]', array(
             'label'	=> esc_html__( 'Check if you want to display the title at the center', 'sparkling' ),
             'section'	=> 'sparkling_maxfu_layout_section',
             'type'      => 'checkbox',
     ));

     // add "Fluid Layout Options" option
     $wp_customize->add_setting( 'sparkling[fluid_layout]', array(
             'default' => 0,
             'type' => 'option',
             'sanitize_callback' => 'sparkling_sanitize_checkbox',
     ));
     $wp_customize->add_control( 'sparkling[fluid_layout]', array(
             'label'	=> esc_html__( 'Check if you want to enable fluid container', 'sparkling' ),
             'section'	=> 'sparkling_maxfu_layout_section',
             'type'      => 'checkbox',
     ));

     // add "Masonry Layout Options" option
     $wp_customize->add_setting( 'sparkling[masonry_layout]', array(
             'default' => 0,
             'type' => 'option',
             'sanitize_callback' => 'sparkling_sanitize_checkbox',
     ));
     $wp_customize->add_control( 'sparkling[masonry_layout]', array(
             'label'	=> esc_html__( 'Check if you want to enable Masonry layout', 'sparkling' ),
             'section'	=> 'sparkling_maxfu_layout_section',
             'type'      => 'checkbox',
     ));
 }
 add_action( 'customize_register', 'sparkling_customizer_maxfu_addon' );
?>
