<?php
/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
 // Add Macland Options to Admin Menu.
 $pages = array(
   'macland-options'   => array(
     'page_title'    => __( 'Macland Options', 'sparkling' ),
     'position'      => 1,
     'sections'      => array(
       'section-one'   => array(
         'title'         => __( 'Homepage Options', 'sparkling' ),
         'fields'        => array(
           'act_pic'         => array(
             'title'         => __( 'Activity Picture' ),
             'id'            => 'activity_pic',
             'type'          => 'media',
             'value'         => '',
             'placeholder'   => 'Click Upload to upload or choose picture for Activity',
           ),
           'act_date'        => array(
             'title'         => __( 'Activity Date' ),
             'id'            => 'activity_date',
             'type'          => 'date',
             'value'         => 'now',
           ),
           'h_slider_1'      => array(
             'title'         => __( 'Home Slider Picrure 1' ),
             'id'            => 'home_slider_1',
             'type'          => 'media',
             'value'         => '',
             'placeholder'   => 'Click Upload to upload or choose the picture.',
           ),
           'h_sl_link_1'     => array(
             'title'         => __( 'Home Slider Link 1' ),
             'id'            => 'home_slider_link_1',
             'type'          => 'url',
             'placeholder'   => 'Link for Home Slider 1',
           ),
           'h_slider_2'      => array(
             'title'         => __( 'Home Slider Picrure 2' ),
             'id'            => 'home_slider_2',
             'type'          => 'media',
             'value'         => '',
             'placeholder'   => 'Click Upload to upload or choose the picture.',
           ),
           'h_sl_link_2'     => array(
             'title'         => __( 'Home Slider Link 2' ),
             'id'            => 'home_slider_link_2',
             'type'          => 'url',
             'placeholder'   => 'Link for Home Slider 2',
           ),
           'h_slider_3'      => array(
             'title'         => __( 'Home Slider Picrure 3' ),
             'id'            => 'home_slider_3',
             'type'          => 'media',
             'value'         => '',
             'placeholder'   => 'Click Upload to upload or choose the picture.',
           ),
           'h_sl_link_3'     => array(
             'title'         => __( 'Home Slider Link 3' ),
             'id'            => 'home_slider_link_3',
             'type'          => 'url',
             'placeholder'   => 'Link for Home Slider 3',
           ),
         ),
       ),
       'section-two'   => array(
         'title'         => __( 'Website Options', 'sparkling' ),
         'fields'        => array(
           'disp_contact'    => array(
             'title'         => __( 'Staff Contact Information' ),
             'id'            => 'display_contact',
             'type'          => 'checkbox',
             'text'          => __( 'Display contact information in Team Page' ),
           ),
           'menu_search'    => array(
             'title'         => __( 'Display Search on Main Menu' ),
             'id'            => 'menu_search',
             'type'          => 'checkbox',
             'text'          => __( 'Display Search on Main Menu. If thrid party menu search plugin installed, uncheck this' ),
           ),
           'comp_tel'        => array(
             'title'         => __( 'Company Telephone' ),
             'id'            => 'company_tel',
             'type'          => 'tel',
             'placeholder'   => '61-2-9736-2888',
           ),
           'comp_fax'        => array(
             'title'         => __( 'Company Fax' ),
             'id'            => 'company_fax',
             'type'          => 'tel',
             'placeholder'   => '61-2-9736-2681',
           ),
           'comp_address'    => array(
             'title'         => __( 'Company Address' ),
             'id'            => 'company_address',
             'text'          => __( 'Text attributes are used as help text for most input types.' ),
             'placeholder'   => 'Suite 601, 5 Rider BLVD Rhodes NSW 2138',
           ),
           'comp_s_weibo'    => array(
             'title'         => __( 'Sina Weibo', 'sparkling' ),
             'id'            => 'company_sina_weibo',
             'type'          => 'url',
             'placeholder'   => 'Link of Sina Weibo',
           ),
           'comp_t_weibo'    => array(
             'title'         => __( 'Sina Weibo', 'sparkling' ),
             'id'            => 'company_tencent_weibo',
             'type'          => 'url',
             'placeholder'   => 'Link of Tencent Weibo',
           ),
           'comp_facebook'   => array(
             'title'         => __( 'Facebook', 'sparkling' ),
             'id'            => 'company_facebook',
             'type'          => 'url',
             'placeholder'   => 'Link of Facebook',
           ),
           'comp_twitter'    => array(
             'title'         => __( 'Twitter', 'sparkling' ),
             'id'            => 'company_twitter',
             'type'          => 'url',
             'placeholder'   => 'Link of Twitter',
           ),
           'comp_linkedin'     => array(
             'title'         => __( 'Linkedin', 'sparkling' ),
             'id'            => 'company_linkedin',
             'type'          => 'url',
             'placeholder'   => 'Link of Linkedin',
           ),
           'comp_wechat'     => array(
             'title'         => __( 'WeChat QrCode' ),
             'id'            => 'company_wechat',
             'type'          => 'media',
             'value'         => '',
             'placeholder'   => 'Click Upload to upload or choose the QrCode.',
           ),
         ),
       ),
     ),
   ),
 );
 $option_page = new RationalOptionPages( $pages );
?>
